version: '2.1'

services:
  mariadb:
    image: mariadb
    container_name: 'wptest-mysql'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: M9e6d3w8e5d2&
      MYSQL_DATABASE: wpt
      MYSQL_USER: wpt
      MYSQL_PASSWORD: M9e6d3w8e5d2&

  php:
    build: ./images/php
    container_name: 'wptest-php'
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_HOST: wptest-mysql
      DB_PASS: M9e6d3w8e5d2&
      DB_NAME: wpt
      DB_USER: wpt
    links:
      - mariadb
    volumes:
      - ./www:/var/www

  nginx:
    image: nginx
    container_name: 'wptest-nginx'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mariadb
      - php
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - mariadb:mariadb
    environment:
      MYSQL_ROOT_PASSWORD: M9e6d3w8e5d2&
      PMA_HOST: mariadb
